# Generated by Django 2.2.14 on 2025-02-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('G', 'Grocery'), ('B', 'Beverages'), ('CF', 'Canned Foods')], max_length=2),
        ),
    ]
